### ISSUE TITLE
Trolls should fall down when badly wounded

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/EE_Fixpack#28]
__Observed:__
Trolls don't fall down when badly wounded. It looks like their falling down animation is triggered but quickly overridden by another script action. They still become vulnerable to fire and acid damage though.

__Expected:__
Trolls fall down when badly wounded and remain in their unconscious state for a while.

Tested in BG2EE and SoD.

**Comment by 4Luke4** [comment]
> It looks like their falling down animation is triggered but quickly overridden by another script action.

How is this possible ...? I mean, I thought that on EE games the entire Trolls fall down mechanics did not rely upon scripts, but only upon `op232`...

Also, now that I think of it, I would use `op272 // p1=1, p2=3: once per second` in place of `op232` (since the former is supposed to trigger faster) and add a leading `op318` effect to `trollreg.spl` checking for `STAT CURHITPOINTS >= 2` (or some other value...)

**Comment by Argent77** [comment]
I could track the issue back to commit ccf774c7646b84a81d8e45db7895dd8ba2dab6da made by @CamDawg .

**Comment by CamDawg** [comment]
I can confirm this is an issue, and directly caused by the new 146s in trollreg.spl. Looking at alternatives now.

**Comment by CamDawg** [comment]
Fixed by https://github.com/CamDawg/EE_Fixpack/commit/01b21e2995efe45645ff7f4a4149b8ae60f095bb

Effectively, moving the cure sleep opcode (2) from the troll fake death spell into the #cureslp spell causing it to fire after the troll's own sleep opcode--so it sleeps to fake death, and then immediately gets cured of sleep. I've basically hacked out an exception where trolls retain op 2, and then block the op 2 from #cureslp, preserving the working effect ordering. It's a bit of a hack, but worked in my testing.

**Comment by Argent77** [comment]
Confirmed as working. Issue can be closed.
